i3 - fix `scratchpad` script (now much more reliable)

diff --git a/i3/.config/i3/scripts/scratchpad b/i3/.config/i3/scripts/scratchpad
--- a/i3/.config/i3/scripts/scratchpad
+++ b/i3/.config/i3/scripts/scratchpad
@@ -52,22 +52,27 @@ if [[ -z "$visible_wid" ]]; then # If the scratchpad window is not visible
       exit 2
     fi
 
-    echo "${name} not found. Executing: '${@: 2}'."
-    if ! eval "${@: 2}" ; then
-      echo "Provided command '${@: 2}' failed"
-      exit $?
-    fi
-    eval "${@: 2}"
+    # Program arguments are ignored
+    # Forking process, so this script is not halted until program closes
+    # This does not catch any errors! (I think)
+    echo "${name} not found. Executing: '${2}'."
+    "$2" &
 
-    # Wait for application to be available
-    while [[ -z "$wid" ]]; do
-      sleep 0.05;
-      wid="$(xdotool search --classname "${name}" | tail -1 2> /dev/null)"
+    # Constantly try to show newly spawned window
+    # Much more reliable than waiting with `xdotool`
+    attempts=0
+    max_attempts=100
+    while [ "$attempts" -lt "$max_attempts" ]; do
+        attempts=$((attempts+1))
+        sleep 0.05;
+        i3-msg "[$selector=\"${name}\"] scratchpad show; \
+          [$selector=\"${name}\"] move position center"
+        if [ "$?" = 0 ]; then
+            exit 0;
+        fi
     done
-
-    i3-msg "[$selector=\"${name}\"] scratchpad show; \
-      [$selector=\"${name}\"] move position center"
-    exit 0
+    notify-send "scratchpad: failed to show '$name', after $max_attempts attempts"
+    exit 69
   fi
 
   echo "${name} found. Showing scratchpad."
